#!/bin/bash
# Script for deploying the package via Travis CI
# Use --dry-run for testing without uploading anything

set -euo pipefail

DRY_RUN=
while [ $# -gt 0 ]
do
  case "$1" in
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    *)
      shift
      ;;
  esac
done

function report_fail() {
    echo $1 >&2
    exit 1
}

stack sdist || report_fail "Failed to package for Hackage."

if [ -z "$DRY_RUN" ]
then
  stack upload . || report_fail "Failed to upload to Hackage."
fi
