name: appendmap
version: "0.1.1"
github: "koterpillar/appendmap"
license: BSD3
author: "Alexey Kotlyarov"
maintainer: "a@koterpillar.com"
copyright: "2018 Alexey Kotlyarov"

extra-source-files:
- README.md
- ChangeLog.md

synopsis: Map with a Semigroup and Monoid instances delegating to Semigroup of the elements
category: Data Structures

description: Please see the README on GitHub at <https://github.com/koterpillar/appendmap#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

tests:
  appendmap-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - appendmap
    - hspec
