#!/usr/bin/env ruby
# Script for deploying the package via Travis CI

require 'fileutils'
require 'json'

# Release to Hackage via Stack

stack_credentials = File.expand_path('~/.stack/upload/credentials.json')
unless File.exists?(stack_credentials)
  FileUtils.mkdir_p(File.dirname(stack_credentials))

  File.open(stack_credentials, 'w') { |f|
    config = {
      :username => ENV['HACKAGE_USERNAME'],
      :password => ENV['HACKAGE_PASSWORD'],
    }
    f.write(config.to_json)
  }
end

hackage_uploaded = system('stack', 'upload', '.', '--no-signature')
if not hackage_uploaded
  exit(1)
end
