#!/bin/sh

echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"

if [ -f configure.ac ]; then autoreconf -i; fi

set -ex

# Add in extra-deps for older snapshots, as necessary
stack --no-terminal --install-ghc $ARGS test --bench --dry-run || ( \
stack --no-terminal $ARGS build cabal-install && \
stack --no-terminal $ARGS solver --update-config)

# Build the dependencies
stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies

set +ex
