name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 5"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        resolver:
          - lts-17
          - lts-16
          - lts-15

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Stack
        run: stack upgrade || curl -sSL https://get.haskellstack.org/ | sh -s - -f
      - name: Set up cache
        uses: actions/cache@v1
        with:
          key: ${{ matrix.resolver }}
          path: ~/.stack
      - name: Find latest LTS release
        id: resolver
        run: echo "::set-output name=resolver::$(./latest-lts ${{ matrix.resolver }})"
      - name: Install dependencies
        run: |
          stack --no-terminal --install-ghc --resolver ${{ steps.resolver.outputs.resolver }} ${{ matrix.extra-args }} test --bench --only-dependencies
      - name: Test
        run: |
          stack --no-terminal --resolver ${{ steps.resolver.outputs.resolver }} ${{ matrix.extra-args }} test --bench --no-run-benchmarks --haddock --no-haddock-deps

  deploy-dry-run:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Stack
        run: stack upgrade || curl -sSL https://get.haskellstack.org/ | sh -s - -f
      - name: Deploy (dry run)
        run: ./deploy --dry-run
